/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeartbeatRouteImport } from './routes/heartbeat'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as IndexRouteImport } from './routes/index'

const HeartbeatRoute = HeartbeatRouteImport.update({
  id: '/heartbeat',
  path: '/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fraud': typeof FraudRoute
  '/heartbeat': typeof HeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fraud': typeof FraudRoute
  '/heartbeat': typeof HeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fraud': typeof FraudRoute
  '/heartbeat': typeof HeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fraud' | '/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fraud' | '/heartbeat'
  id: '__root__' | '/' | '/fraud' | '/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FraudRoute: typeof FraudRoute
  HeartbeatRoute: typeof HeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/heartbeat': {
      id: '/heartbeat'
      path: '/heartbeat'
      fullPath: '/heartbeat'
      preLoaderRoute: typeof HeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FraudRoute: FraudRoute,
  HeartbeatRoute: HeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
